image: jangrewe/gitlab-ci-android

stages:
  - buildDebug

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - apt-get -qq update
  - apt-get install -qqy --no-install-recommends build-essential ruby-full
  - gem install bundler
  - bundle install
  - gem install bundler fastlane

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

buildDebug:
  stage: buildDebug
  script:
    - bundle exec fastlane buildDebug
  artifacts:
    paths:
      - app/build/outputs/apk/**/**/*.apk