version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  android: "1.0.3"

jobs:
  build:
    executor:
      name: android/android-machine
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: android buildDebug
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan