version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
    environment:
      FL_OUTPUT_DIR: app/build/outputs/apk/**/**/*.apk
      FASTLANE_LANE: android buildDebug
    steps:
      - checkout
      - run: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  sample:
    jobs:
      - build